export const baseURL = process.env.NEXT_PUBLIC_API_URL || "";

const api = {
  register:              { url: "/api/user/register",            method: "post" },
  verifyEmail:           { url: "/api/user/verify-email",        method: "post" },
  resendVerificationOtp: { url: "/api/user/resend-verification-otp", method: "post" },
  login:                 { url: "/api/user/login",               method: "post" },
  logout:                { url: "/api/user/logout",              method: "get"  },
  uploadAvatar:          { url: "/api/user/upload-avatar",       method: "put"  },
  updateUserDetails:     { url: "/api/user/update-account",      method: "put"  },
  forgotPassword:        { url: "/api/user/forgot-password",     method: "put"  },
  verifyForgotPasswordOtp:{ url:"/api/user/verify-forgot-password-otp", method:"put"},
  resetPassword:         { url: "/api/user/reset-password",      method: "put"  },
  refreshToken:          { url: "/api/user/refresh-token",       method: "post" },
  userDetails:           { url: "/api/user/user-details",        method: "get"  },
  getAllUsers:            { url: "/api/user/all-users",           method: "get"  },
  updateUserRole:        { url: "/api/user/update-role",         method: "put"  },
  addCategory:           { url: "/api/category/add-category",    method: "post" },
  getCategory:           { url: "/api/category/get",             method: "get"  },
  updateCategory:        { url: "/api/category/update",          method: "put"  },
  deleteCategory:        { url: "/api/category/delete",          method: "delete"},
  addSubCategory:        { url: "/api/subcategory/add",          method: "post" },
  getSubCategory:        { url: "/api/subcategory/get",          method: "get"  },
  updateSubCategory:     { url: "/api/subcategory/update",       method: "put"  },
  deleteSubCategory:     { url: "/api/subcategory/delete",       method: "delete"},
  addProduct:            { url: "/api/product/add",              method: "post" },
  getProduct:            { url: "/api/product/get",              method: "post" },
  getProductByCategory:  { url: "/api/product/get-product-by-category", method:"post"},
  getProductByCategoryAndSubCategory:{ url:"/api/product/get-product-by-category-and-subcategory", method:"post"},
  getProductDetails:     { url: "/api/product/get-product-details", method:"post"},
  getProducts:           { url: "/api/product/get",             method: "post" },
  updateProduct:         { url: "/api/product/update",           method: "put"  },
  deleteProduct:         { url: "/api/product/delete",           method: "delete"},
  searchProduct:         { url: "/api/product/search",           method: "post" },
  addToCart:             { url: "/api/cart/add",                 method: "post" },
  getCartItems:          { url: "/api/cart/get",                 method: "get"  },
  updateCartItemQty:     { url: "/api/cart/update-qty",          method: "put"  },
  deleteCartItem:        { url: "/api/cart/delete",              method: "delete"},
  clearCart:             { url: "/api/cart/clear",               method: "delete"},
  addAddress:            { url: "/api/address/add",              method: "post" },
  getAddress:            { url: "/api/address/get",              method: "get"  },
  updateAddress:         { url: "/api/address/update",           method: "put"  },
  deleteAddress:         { url: "/api/address/delete",           method: "delete"},
  cashOnDeliveryOrder:   { url: "/api/order/cash-on-delivery",   method: "post" },
  payCodDeliveryCharge:  { url: "/api/order/pay-delivery-charge",method: "post" },
  checkoutOrder:         { url: "/api/order/checkout",           method: "post" },
  getOrderList:          { url: "/api/order/order-list",         method: "get"  },
  getAllOrders:           { url: "/api/order/all-orders",         method: "get"  },
  updateOrderStatus:     { url: "/api/order/update-status",      method: "put"  },
  cancelOwnOrder:        { url: "/api/order/cancel",             method: "put"  },
  uploadImage:           { url: "/api/file/upload",              method: "post" },
  getSiteSettings:       { url: "/api/settings/get",             method: "get"  },
  updateSiteSettings:    { url: "/api/settings/update",          method: "put"  },
  addBanner:             { url: "/api/settings/banner/add",      method: "post" },
  deleteBanner:          { url: "/api/settings/banner/delete",   method: "delete"},
  // Fix (payment logos never persisted): mirrors addBanner/deleteBanner above —
  // a dedicated endpoint that saves immediately, instead of only updating local
  // React state + optimistically dispatching to Redux with no DB write at all.
  addPaymentMethod:      { url: "/api/settings/payment-method/add",    method: "post"  },
  deletePaymentMethod:   { url: "/api/settings/payment-method/delete", method: "delete"},
  // Flash Sales
  // Campaigns (admin-named promo sections — defaults to "Flash Sale" look if unnamed)
  getActiveCampaigns:    { url: "/api/campaigns/active",        method: "get"  },
  getAllCampaigns:       { url: "/api/campaigns/all",           method: "get"  },
  createCampaign:        { url: "/api/campaigns/create",        method: "post" },
  updateCampaign:        { url: "/api/campaigns/update",        method: "put"  },
  deleteCampaign:        { url: "/api/campaigns/delete",        method: "delete"},
  addProductToCampaign:  { url: "/api/campaigns/add-product",   method: "post" },
  removeProductFromCampaign:{ url:"/api/campaigns/remove-product",method:"post"},
  // Coupons
  validateCoupon:        { url: "/api/coupons/validate",         method: "post" },
  getActiveCoupons:      { url: "/api/coupons/active",           method: "get"  },
  getAllCoupons:          { url: "/api/coupons/all",              method: "get"  },
  createCoupon:          { url: "/api/coupons/create",           method: "post" },
  updateCoupon:          { url: "/api/coupons/update",           method: "put"  },
  deleteCoupon:          { url: "/api/coupons/delete",           method: "delete"},
  // Analytics
  getDashboardMetrics:   { url: "/api/analytics/dashboard",      method: "get"  },
  getTrending:           { url: "/api/analytics/trending",       method: "get"  },
  getBestSelling:        { url: "/api/analytics/best-selling",   method: "get"  },
  getLowSelling:         { url: "/api/analytics/low-selling",    method: "get"  },
  getNeverSold:          { url: "/api/analytics/never-sold",     method: "get"  },
  getAllTimeBest:         { url: "/api/analytics/all-time-best",  method: "get"  },
  // Inventory
  getInventory:          { url: "/api/inventory/list",           method: "get"  },
  adjustStock:           { url: "/api/inventory/adjust",         method: "post" },
  getInventoryLogs:      { url: "/api/inventory/logs",           method: "get"  },
  getLowStock:           { url: "/api/inventory/low-stock",      method: "get"  },
  // Activity
  logActivity:           { url: "/api/activity/log",             method: "post" },
  getSuggestions:        { url: "/api/activity/suggestions",     method: "get"  },
  getRecentlyViewed:     { url: "/api/activity/recently-viewed", method: "get"  },
  // Roles (RBAC)
  getAllRoles:            { url: "/api/roles/all",                method: "get"  },
  createRole:            { url: "/api/roles/create",             method: "post" },
  updateRole:            { url: "/api/roles/update",             method: "put"  },
  deleteRole:            { url: "/api/roles/delete",             method: "delete"},
  assignUserRole:        { url: "/api/roles/assign",             method: "put"  },
  getMyPermissions:      { url: "/api/roles/my-permissions",     method: "get"  },
  // Customers
  getCustomers:          { url: "/api/customers/list",           method: "get"  },
  exportCustomers:       { url: "/api/customers/export",         method: "get"  },
  getCustomerDetail:     { url: "/api/customers",                method: "get"  }, // + /:id
  // Currency
  getExchangeRates:      { url: "/api/currency/rates",           method: "get"  },
  // Delivery Zones
  quoteDeliveryCharge:   { url: "/api/delivery-zones/quote",     method: "get"  },
  getActiveZones:        { url: "/api/delivery-zones/active",    method: "get"  },
  getAllDeliveryZones:   { url: "/api/delivery-zones/all",       method: "get"  },
  createDeliveryZone:    { url: "/api/delivery-zones/create",    method: "post" },
  updateDeliveryZone:    { url: "/api/delivery-zones/update",    method: "put"  },
  deleteDeliveryZone:    { url: "/api/delivery-zones/delete",    method: "delete"},
  // FAQ
  getFaqs:               { url: "/api/settings/faq",             method: "get"  },
  manageFaq:             { url: "/api/settings/faq",             method: "put"  },
  // Fix 4: Notifications
  getNotifications:      { url: "/api/notification/list",        method: "get"  },
  markNotificationRead:  { url: "/api/notification/mark-read",   method: "put"  },
  markAllNotificationsRead: { url: "/api/notification/mark-all-read", method: "put" },
  // Product Requests (customer-submitted shopping lists — text or photo)
  submitProductRequest:  { url: "/api/product-requests/submit",  method: "post" },
  getMyProductRequests:  { url: "/api/product-requests/mine",    method: "get"  },
  getAllProductRequests: { url: "/api/product-requests/all",     method: "get"  },
  updateProductRequestStatus:{ url: "/api/product-requests/update-status", method: "put" },
  // Barcode
  lookupBarcode:         { url: "/api/barcode/lookup",           method: "get"  },
  barcodeQuickSale:      { url: "/api/barcode/quick-sale",       method: "post" },
  // Fix 26: Customer Care
  getTickets:            { url: "/api/customer-care/list",       method: "get"  },
  createTicket:          { url: "/api/customer-care/create",     method: "post" },
  updateTicket:          { url: "/api/customer-care/update",     method: "put"  },
  deleteTicket:          { url: "/api/customer-care/delete",     method: "delete"},
  getCareOrders:         { url: "/api/customer-care/orders",     method: "get"  },
  updateCareOrderStatus: { url: "/api/customer-care/orders/status", method: "put" },
  getCallCenterAgents:   { url: "/api/customer-care/agents",     method: "get"  },
  createCallCenterAgent: { url: "/api/customer-care/agents",     method: "post" },
  updateCallCenterAgent: { url: "/api/customer-care/agents",     method: "put"  },
  deleteCallCenterAgent: { url: "/api/customer-care/agents",     method: "delete"},
  logCallInitiated:      { url: "/api/customer-care/calls/initiate", method: "post" },
  logCallOutcome:        { url: "/api/customer-care/calls/outcome",  method: "put"  },
  getMyPendingCallLogs:  { url: "/api/customer-care/calls/pending",  method: "get"  },
  getCallHistory:        { url: "/api/customer-care/calls/history", method: "get"  },
  // Fix 26: HR & Payroll
  getEmployees:          { url: "/api/hr-payroll/employees",     method: "get"  },
  createEmployee:        { url: "/api/hr-payroll/employees",     method: "post" },
  updateEmployee:        { url: "/api/hr-payroll/employees",     method: "put"  },
  deleteEmployee:        { url: "/api/hr-payroll/employees",     method: "delete"},
  getPayroll:            { url: "/api/hr-payroll/payroll",       method: "get"  },
  savePayroll:           { url: "/api/hr-payroll/payroll",       method: "post" },
  // Fix 34: Analytics settings (dependencies / key values)
  getAnalyticsSettings:  { url: "/api/analytics/settings",       method: "get"  },
  updateAnalyticsSettings:{ url: "/api/analytics/settings",      method: "put"  },
  // Fix 35-40: Analytics tab data
  getFinancialMetrics:   { url: "/api/analytics/financial",      method: "get"  },
  getInventorySalesMetrics:{ url: "/api/analytics/inventory-sales", method: "get" },
  getCustomerOrderMetrics:{ url: "/api/analytics/customer-order", method: "get" },
  getMarketingMetrics:   { url: "/api/analytics/marketing",      method: "get"  },
  getExpenseAnalysis:    { url: "/api/analytics/expenses",       method: "get"  },
  // Fix 36: Damaged inventory
  markDamaged:           { url: "/api/inventory/mark-damaged",   method: "post" },
  getDamagedInventory:   { url: "/api/inventory/damaged",        method: "get"  },
  // Fix 17: Activity/session tracking summary for admin
  getActivitySummary:    { url: "/api/activity/summary",         method: "get"  },
  // Fix 23: SEO
  getSitemapUrls:        { url: "/api/settings/sitemap-urls",    method: "get"  },
  // Fix 27: Google OAuth
  googleAuth:            { url: "/api/user/google-auth",         method: "post" },
};

export default api;
