// Generates /etc/asterisk/pjsip_agents.conf from every provisioned
// call-center agent in MongoDB, following the endpoint/auth/aor
// template documented at the bottom of asterisk-config/pjsip.conf.
//
// Run this on your VPS (not in this sandbox — it needs a real MongoDB
// connection and Asterisk installed) whenever agents are added or
// removed:
//   node src/modules/callcenter/telephony/generatePjsipConfig.js
//   asterisk -rx "pjsip reload"
//
// Or wire it into your deployment/CI so it runs automatically after
// any agent-provisioning change — the query below is read-only and
// cheap, safe to run on a schedule (e.g. a 5-minute cron) if you'd
// rather not remember to run it by hand.

import connectDb from "../socket/dbConnectForServer.js";
import EmployeeModel from "../../../server/models/employee.model.js";
import fs from "fs";

const OUTPUT_PATH = process.env.PJSIP_AGENTS_CONF_PATH || "/etc/asterisk/pjsip_agents.conf";

async function main() {
  await connectDb();
  const agents = await EmployeeModel.find({ isCallCenterAgent: true, sipUsername: { $ne: null } }).select("name sipUsername sipPassword");

  const blocks = agents.map((a) => `
[agent-${a.sipUsername}]
type=endpoint
transport=transport-wss
context=agents-outbound
disallow=all
allow=opus,ulaw,alaw
webrtc=yes
dtls_auto_generate_cert=yes
use_avpf=yes
media_encryption=dtls
ice_support=yes
rtcp_mux=yes
auth=agent-${a.sipUsername}-auth
aors=agent-${a.sipUsername}-aor
callerid=${(a.name || "Agent").replace(/[^\w\s]/g, "")} <${a.sipUsername}>

[agent-${a.sipUsername}-auth]
type=auth
auth_type=userpass
username=${a.sipUsername}
password=${a.sipPassword}

[agent-${a.sipUsername}-aor]
type=aor
max_contacts=1
remove_existing=yes
`.trim());

  const header = `; AUTO-GENERATED by generatePjsipConfig.js — DO NOT EDIT BY HAND.\n; Regenerate after any agent create/delete, then: asterisk -rx "pjsip reload"\n; Generated at: ${new Date().toISOString()}\n; ${agents.length} agent(s)\n`;

  fs.writeFileSync(OUTPUT_PATH, `${header}\n${blocks.join("\n\n")}\n`);
  console.log(`Wrote ${agents.length} agent endpoint(s) to ${OUTPUT_PATH}`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Failed to generate pjsip_agents.conf:", err);
  process.exit(1);
});
